---
title: "TEMPLATE"
author:
- Office of Decision Support
- University of Nevada, Las Vegas
date: "`r paste0('Last Updated: ', format(Sys.Date(),'%B %d, %Y'))`"
output:
  pdf_document: default
  word_document: default
header-includes:
- \usepackage[utf8]{inputenc}
- \usepackage[T1]{fontenc}
- \usepackage{textcomp}
- \usepackage{float}
---

```{r setup, include = FALSE}
## My favorite packages
library(xtable)
library(ggplot2)
library(dplyr)
library(tidyr)
library(purrr)

if (Sys.info()[["sysname"]]=="Windows") {
  beg_path <- "X:/" 
} else {
  beg_path <- "/Volumes/Staff/"
} 

source(paste0(beg_path, "Groups/Decision Support/Exchange/Shiloh/R/utilities_make_db_con.R")) ## Database connection
source(paste0(beg_path, "Groups/Decision Support/Exchange/Shiloh/R/functions_Shiloh.R")) ## A file of custom functions
```

```{r Functions, echo = FALSE, results = 'asis'}
## Your custom functions here
```

```{r Parameters, echo = FALSE, results = 'asis'}
## Your custom parameters here
maxrows <- 10
```

```{sql Example Query, connection = db_con, output.var = "trials"}
-- Example SQL Query
SELECT distinct strm FROM ps_lv_cnr_terms WHERE rownum < ?maxrows
```

```{r Example Chunk, echo = FALSE, results = 'asis'}
## Example R Chunk
print(trials)
```
